/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.deepak.sudoku;

/**
 *
 * @author YATRAONLINE\deepak.singh2
 */
public class SudokuFrame extends javax.swing.JFrame {

	/**
	 * Creates new form SudokuFrame
	 */
	public SudokuFrame() {
		initComponents();
		setLocationRelativeTo(this);
		setResizable(false);
		setTitle("Sudoku Solver");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jTextField10 = new javax.swing.JTextField();
		jTextField11 = new javax.swing.JTextField();
		jTextField12 = new javax.swing.JTextField();
		jTextField13 = new javax.swing.JTextField();
		jTextField14 = new javax.swing.JTextField();
		jTextField15 = new javax.swing.JTextField();
		jTextField16 = new javax.swing.JTextField();
		jTextField17 = new javax.swing.JTextField();
		jTextField18 = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jTextField19 = new javax.swing.JTextField();
		jTextField20 = new javax.swing.JTextField();
		jTextField21 = new javax.swing.JTextField();
		jTextField22 = new javax.swing.JTextField();
		jTextField23 = new javax.swing.JTextField();
		jTextField24 = new javax.swing.JTextField();
		jTextField25 = new javax.swing.JTextField();
		jTextField26 = new javax.swing.JTextField();
		jTextField27 = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jTextField28 = new javax.swing.JTextField();
		jTextField29 = new javax.swing.JTextField();
		jTextField30 = new javax.swing.JTextField();
		jTextField31 = new javax.swing.JTextField();
		jTextField32 = new javax.swing.JTextField();
		jTextField33 = new javax.swing.JTextField();
		jTextField34 = new javax.swing.JTextField();
		jTextField35 = new javax.swing.JTextField();
		jTextField36 = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jTextField37 = new javax.swing.JTextField();
		jTextField38 = new javax.swing.JTextField();
		jTextField39 = new javax.swing.JTextField();
		jTextField40 = new javax.swing.JTextField();
		jTextField41 = new javax.swing.JTextField();
		jTextField42 = new javax.swing.JTextField();
		jTextField43 = new javax.swing.JTextField();
		jTextField44 = new javax.swing.JTextField();
		jTextField45 = new javax.swing.JTextField();
		jPanel6 = new javax.swing.JPanel();
		jTextField46 = new javax.swing.JTextField();
		jTextField47 = new javax.swing.JTextField();
		jTextField48 = new javax.swing.JTextField();
		jTextField49 = new javax.swing.JTextField();
		jTextField50 = new javax.swing.JTextField();
		jTextField51 = new javax.swing.JTextField();
		jTextField52 = new javax.swing.JTextField();
		jTextField53 = new javax.swing.JTextField();
		jTextField54 = new javax.swing.JTextField();
		jPanel7 = new javax.swing.JPanel();
		jTextField55 = new javax.swing.JTextField();
		jTextField56 = new javax.swing.JTextField();
		jTextField57 = new javax.swing.JTextField();
		jTextField58 = new javax.swing.JTextField();
		jTextField59 = new javax.swing.JTextField();
		jTextField60 = new javax.swing.JTextField();
		jTextField61 = new javax.swing.JTextField();
		jTextField62 = new javax.swing.JTextField();
		jTextField63 = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		jTextField64 = new javax.swing.JTextField();
		jTextField65 = new javax.swing.JTextField();
		jTextField66 = new javax.swing.JTextField();
		jTextField67 = new javax.swing.JTextField();
		jTextField68 = new javax.swing.JTextField();
		jTextField69 = new javax.swing.JTextField();
		jTextField70 = new javax.swing.JTextField();
		jTextField71 = new javax.swing.JTextField();
		jTextField72 = new javax.swing.JTextField();
		jPanel9 = new javax.swing.JPanel();
		jTextField73 = new javax.swing.JTextField();
		jTextField74 = new javax.swing.JTextField();
		jTextField75 = new javax.swing.JTextField();
		jTextField76 = new javax.swing.JTextField();
		jTextField77 = new javax.swing.JTextField();
		jTextField78 = new javax.swing.JTextField();
		jTextField79 = new javax.swing.JTextField();
		jTextField80 = new javax.swing.JTextField();
		jTextField81 = new javax.swing.JTextField();
		solveButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(500, 555));
		setResizable(false);
		setSize(new java.awt.Dimension(500, 555));

		mainPanel.setMinimumSize(new java.awt.Dimension(500, 500));
		mainPanel.setPreferredSize(new java.awt.Dimension(500, 500));
		mainPanel.setLayout(new java.awt.GridLayout(3, 3));

		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setLayout(new java.awt.GridLayout(3, 3));

		jTextField1.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField1.setText(".");
		jPanel1.add(jTextField1);

		jTextField2.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField2.setText(".");
		jPanel1.add(jTextField2);

		jTextField3.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField3.setText(".");
		jPanel1.add(jTextField3);

		jTextField4.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField4.setText(".");
		jPanel1.add(jTextField4);

		jTextField5.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField5.setText(".");
		jPanel1.add(jTextField5);

		jTextField6.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField6.setText(".");
		jPanel1.add(jTextField6);

		jTextField7.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField7.setText(".");
		jPanel1.add(jTextField7);

		jTextField8.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField8.setText(".");
		jPanel1.add(jTextField8);

		jTextField9.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField9.setText(".");
		jPanel1.add(jTextField9);

		mainPanel.add(jPanel1);

		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel2.setLayout(new java.awt.GridLayout(3, 3));

		jTextField10.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField10.setText(".");
		jPanel2.add(jTextField10);

		jTextField11.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField11.setText(".");
		jPanel2.add(jTextField11);

		jTextField12.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField12.setText(".");
		jPanel2.add(jTextField12);

		jTextField13.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField13.setText(".");
		jPanel2.add(jTextField13);

		jTextField14.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField14.setText(".");
		jPanel2.add(jTextField14);

		jTextField15.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField15.setText(".");
		jPanel2.add(jTextField15);

		jTextField16.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField16.setText(".");
		jPanel2.add(jTextField16);

		jTextField17.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField17.setText(".");
		jPanel2.add(jTextField17);

		jTextField18.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField18.setText(".");
		jPanel2.add(jTextField18);

		mainPanel.add(jPanel2);

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel3.setLayout(new java.awt.GridLayout(3, 3));

		jTextField19.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField19.setText(".");
		jPanel3.add(jTextField19);

		jTextField20.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField20.setText(".");
		jPanel3.add(jTextField20);

		jTextField21.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField21.setText(".");
		jPanel3.add(jTextField21);

		jTextField22.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField22.setText(".");
		jPanel3.add(jTextField22);

		jTextField23.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField23.setText(".");
		jPanel3.add(jTextField23);

		jTextField24.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField24.setText(".");
		jPanel3.add(jTextField24);

		jTextField25.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField25.setText(".");
		jPanel3.add(jTextField25);

		jTextField26.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField26.setText(".");
		jPanel3.add(jTextField26);

		jTextField27.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField27.setText(".");
		jPanel3.add(jTextField27);

		mainPanel.add(jPanel3);

		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel4.setLayout(new java.awt.GridLayout(3, 3));

		jTextField28.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField28.setText(".");
		jPanel4.add(jTextField28);

		jTextField29.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField29.setText(".");
		jPanel4.add(jTextField29);

		jTextField30.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField30.setText(".");
		jPanel4.add(jTextField30);

		jTextField31.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField31.setText(".");
		jPanel4.add(jTextField31);

		jTextField32.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField32.setText(".");
		jPanel4.add(jTextField32);

		jTextField33.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField33.setText(".");
		jPanel4.add(jTextField33);

		jTextField34.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField34.setText(".");
		jPanel4.add(jTextField34);

		jTextField35.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField35.setText(".");
		jPanel4.add(jTextField35);

		jTextField36.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField36.setText(".");
		jPanel4.add(jTextField36);

		mainPanel.add(jPanel4);

		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel5.setLayout(new java.awt.GridLayout(3, 3));

		jTextField37.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField37.setText(".");
		jPanel5.add(jTextField37);

		jTextField38.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField38.setText(".");
		jPanel5.add(jTextField38);

		jTextField39.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField39.setText(".");
		jPanel5.add(jTextField39);

		jTextField40.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField40.setText(".");
		jPanel5.add(jTextField40);

		jTextField41.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField41.setText(".");
		jPanel5.add(jTextField41);

		jTextField42.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField42.setText(".");
		jPanel5.add(jTextField42);

		jTextField43.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField43.setText(".");
		jPanel5.add(jTextField43);

		jTextField44.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField44.setText(".");
		jPanel5.add(jTextField44);

		jTextField45.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField45.setText(".");
		jPanel5.add(jTextField45);

		mainPanel.add(jPanel5);

		jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel6.setLayout(new java.awt.GridLayout(3, 3));

		jTextField46.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField46.setText(".");
		jPanel6.add(jTextField46);

		jTextField47.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField47.setText(".");
		jPanel6.add(jTextField47);

		jTextField48.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField48.setText(".");
		jPanel6.add(jTextField48);

		jTextField49.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField49.setText(".");
		jPanel6.add(jTextField49);

		jTextField50.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField50.setText(".");
		jPanel6.add(jTextField50);

		jTextField51.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField51.setText(".");
		jPanel6.add(jTextField51);

		jTextField52.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField52.setText(".");
		jPanel6.add(jTextField52);

		jTextField53.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField53.setText(".");
		jPanel6.add(jTextField53);

		jTextField54.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField54.setText(".");
		jPanel6.add(jTextField54);

		mainPanel.add(jPanel6);

		jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel7.setLayout(new java.awt.GridLayout(3, 3));

		jTextField55.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField55.setText(".");
		jPanel7.add(jTextField55);

		jTextField56.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField56.setText(".");
		jPanel7.add(jTextField56);

		jTextField57.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField57.setText(".");
		jPanel7.add(jTextField57);

		jTextField58.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField58.setText(".");
		jPanel7.add(jTextField58);

		jTextField59.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField59.setText(".");
		jPanel7.add(jTextField59);

		jTextField60.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField60.setText(".");
		jPanel7.add(jTextField60);

		jTextField61.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField61.setText(".");
		jPanel7.add(jTextField61);

		jTextField62.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField62.setText(".");
		jPanel7.add(jTextField62);

		jTextField63.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField63.setText(".");
		jPanel7.add(jTextField63);

		mainPanel.add(jPanel7);

		jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel8.setLayout(new java.awt.GridLayout(3, 3));

		jTextField64.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField64.setText(".");
		jPanel8.add(jTextField64);

		jTextField65.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField65.setText(".");
		jPanel8.add(jTextField65);

		jTextField66.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField66.setText(".");
		jPanel8.add(jTextField66);

		jTextField67.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField67.setText(".");
		jPanel8.add(jTextField67);

		jTextField68.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField68.setText(".");
		jPanel8.add(jTextField68);

		jTextField69.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField69.setText(".");
		jPanel8.add(jTextField69);

		jTextField70.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField70.setText(".");
		jPanel8.add(jTextField70);

		jTextField71.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField71.setText(".");
		jPanel8.add(jTextField71);

		jTextField72.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField72.setText(".");
		jPanel8.add(jTextField72);

		mainPanel.add(jPanel8);

		jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel9.setLayout(new java.awt.GridLayout(3, 3));

		jTextField73.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField73.setText(".");
		jPanel9.add(jTextField73);

		jTextField74.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField74.setText(".");
		jPanel9.add(jTextField74);

		jTextField75.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField75.setText(".");
		jPanel9.add(jTextField75);

		jTextField76.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField76.setText(".");
		jPanel9.add(jTextField76);

		jTextField77.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField77.setText(".");
		jPanel9.add(jTextField77);

		jTextField78.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField78.setText(".");
		jPanel9.add(jTextField78);

		jTextField79.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField79.setText(".");
		jPanel9.add(jTextField79);

		jTextField80.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField80.setText(".");
		jPanel9.add(jTextField80);

		jTextField81.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
		jTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jTextField81.setText(".");
		jPanel9.add(jTextField81);

		mainPanel.add(jPanel9);

		solveButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		solveButton.setText("Solve");
		solveButton.setToolTipText("Solve Sudoku");
		solveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		solveButton.setMaximumSize(new java.awt.Dimension(500, 555));
		solveButton.setMinimumSize(new java.awt.Dimension(52, 30));
		solveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				solveButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup().addGap(199, 199, 199).addComponent(solveButton,
						javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(1, 1, 1)
										.addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(solveButton, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap()));

		pack();
	}// </editor-fold>

	private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {
		char[][] board = new char[9][9];

		// first block

		board[0][0] = jTextField1.getText().charAt(0);
		board[0][1] = jTextField2.getText().charAt(0);
		board[0][2] = jTextField3.getText().charAt(0);
		board[1][0] = jTextField4.getText().charAt(0);
		board[1][1] = jTextField5.getText().charAt(0);
		board[1][2] = jTextField6.getText().charAt(0);
		board[2][0] = jTextField7.getText().charAt(0);
		board[2][1] = jTextField8.getText().charAt(0);
		board[2][2] = jTextField9.getText().charAt(0);

		// second block

		board[0][3] = jTextField10.getText().charAt(0);
		board[0][4] = jTextField11.getText().charAt(0);
		board[0][5] = jTextField12.getText().charAt(0);
		board[1][3] = jTextField13.getText().charAt(0);
		board[1][4] = jTextField14.getText().charAt(0);
		board[1][5] = jTextField15.getText().charAt(0);
		board[2][3] = jTextField16.getText().charAt(0);
		board[2][4] = jTextField17.getText().charAt(0);
		board[2][5] = jTextField18.getText().charAt(0);

		// third block

		board[0][6] = jTextField19.getText().charAt(0);
		board[0][7] = jTextField20.getText().charAt(0);
		board[0][8] = jTextField21.getText().charAt(0);
		board[1][6] = jTextField22.getText().charAt(0);
		board[1][7] = jTextField23.getText().charAt(0);
		board[1][8] = jTextField24.getText().charAt(0);
		board[2][6] = jTextField25.getText().charAt(0);
		board[2][7] = jTextField26.getText().charAt(0);
		board[2][8] = jTextField27.getText().charAt(0);

		// fourth block

		board[3][0] = jTextField28.getText().charAt(0);
		board[3][1] = jTextField29.getText().charAt(0);
		board[3][2] = jTextField30.getText().charAt(0);
		board[4][0] = jTextField31.getText().charAt(0);
		board[4][1] = jTextField32.getText().charAt(0);
		board[4][2] = jTextField33.getText().charAt(0);
		board[5][0] = jTextField34.getText().charAt(0);
		board[5][1] = jTextField35.getText().charAt(0);
		board[5][2] = jTextField36.getText().charAt(0);

		// fifth block

		board[3][3] = jTextField37.getText().charAt(0);
		board[3][4] = jTextField38.getText().charAt(0);
		board[3][5] = jTextField39.getText().charAt(0);
		board[4][3] = jTextField40.getText().charAt(0);
		board[4][4] = jTextField41.getText().charAt(0);
		board[4][5] = jTextField42.getText().charAt(0);
		board[5][3] = jTextField43.getText().charAt(0);
		board[5][4] = jTextField44.getText().charAt(0);
		board[5][5] = jTextField45.getText().charAt(0);

		// sixth block

		board[3][6] = jTextField46.getText().charAt(0);
		board[3][7] = jTextField47.getText().charAt(0);
		board[3][8] = jTextField48.getText().charAt(0);
		board[4][6] = jTextField49.getText().charAt(0);
		board[4][7] = jTextField50.getText().charAt(0);
		board[4][8] = jTextField51.getText().charAt(0);
		board[5][6] = jTextField52.getText().charAt(0);
		board[5][7] = jTextField53.getText().charAt(0);
		board[5][8] = jTextField54.getText().charAt(0);

		// seventh block

		board[6][0] = jTextField55.getText().charAt(0);
		board[6][1] = jTextField56.getText().charAt(0);
		board[6][2] = jTextField57.getText().charAt(0);
		board[7][0] = jTextField58.getText().charAt(0);
		board[7][1] = jTextField59.getText().charAt(0);
		board[7][2] = jTextField60.getText().charAt(0);
		board[8][0] = jTextField61.getText().charAt(0);
		board[8][1] = jTextField62.getText().charAt(0);
		board[8][2] = jTextField63.getText().charAt(0);

		// eighth block

		board[6][3] = jTextField64.getText().charAt(0);
		board[6][4] = jTextField65.getText().charAt(0);
		board[6][5] = jTextField66.getText().charAt(0);
		board[7][3] = jTextField67.getText().charAt(0);
		board[7][4] = jTextField68.getText().charAt(0);
		board[7][5] = jTextField69.getText().charAt(0);
		board[8][3] = jTextField70.getText().charAt(0);
		board[8][4] = jTextField71.getText().charAt(0);
		board[8][5] = jTextField72.getText().charAt(0);

		// ninth block

		board[6][6] = jTextField73.getText().charAt(0);
		board[6][7] = jTextField74.getText().charAt(0);
		board[6][8] = jTextField75.getText().charAt(0);
		board[7][6] = jTextField76.getText().charAt(0);
		board[7][7] = jTextField77.getText().charAt(0);
		board[7][8] = jTextField78.getText().charAt(0);
		board[8][6] = jTextField79.getText().charAt(0);
		board[8][7] = jTextField80.getText().charAt(0);
		board[8][8] = jTextField81.getText().charAt(0);

		new Solver().solveSudoku(board);

		// first block

		jTextField1.setText(String.valueOf(board[0][0]));
		jTextField2.setText(String.valueOf(board[0][1]));
		jTextField3.setText(String.valueOf(board[0][2]));
		jTextField4.setText(String.valueOf(board[1][0]));
		jTextField5.setText(String.valueOf(board[1][1]));
		jTextField6.setText(String.valueOf(board[1][2]));
		jTextField7.setText(String.valueOf(board[2][0]));
		jTextField8.setText(String.valueOf(board[2][1]));
		jTextField9.setText(String.valueOf(board[2][2]));

		// second block

		jTextField10.setText(String.valueOf(board[0][3]));
		jTextField11.setText(String.valueOf(board[0][4]));
		jTextField12.setText(String.valueOf(board[0][5]));
		jTextField13.setText(String.valueOf(board[1][3]));
		jTextField14.setText(String.valueOf(board[1][4]));
		jTextField15.setText(String.valueOf(board[1][5]));
		jTextField16.setText(String.valueOf(board[2][3]));
		jTextField17.setText(String.valueOf(board[2][4]));
		jTextField18.setText(String.valueOf(board[2][5]));

		// third block

		jTextField19.setText(String.valueOf(board[0][6]));
		jTextField20.setText(String.valueOf(board[0][7]));
		jTextField21.setText(String.valueOf(board[0][8]));
		jTextField22.setText(String.valueOf(board[1][6]));
		jTextField23.setText(String.valueOf(board[1][7]));
		jTextField24.setText(String.valueOf(board[1][8]));
		jTextField25.setText(String.valueOf(board[2][6]));
		jTextField26.setText(String.valueOf(board[2][7]));
		jTextField27.setText(String.valueOf(board[2][8]));

		// fourth block

		jTextField28.setText(String.valueOf(board[3][0]));
		jTextField29.setText(String.valueOf(board[3][1]));
		jTextField30.setText(String.valueOf(board[3][2]));
		jTextField31.setText(String.valueOf(board[4][0]));
		jTextField32.setText(String.valueOf(board[4][1]));
		jTextField33.setText(String.valueOf(board[4][2]));
		jTextField34.setText(String.valueOf(board[5][0]));
		jTextField35.setText(String.valueOf(board[5][1]));
		jTextField36.setText(String.valueOf(board[5][2]));

		// fifth block

		jTextField37.setText(String.valueOf(board[3][3]));
		jTextField38.setText(String.valueOf(board[3][4]));
		jTextField39.setText(String.valueOf(board[3][5]));
		jTextField40.setText(String.valueOf(board[4][3]));
		jTextField41.setText(String.valueOf(board[4][4]));
		jTextField42.setText(String.valueOf(board[4][5]));
		jTextField43.setText(String.valueOf(board[5][3]));
		jTextField44.setText(String.valueOf(board[5][4]));
		jTextField45.setText(String.valueOf(board[5][5]));

		// sixth block

		jTextField46.setText(String.valueOf(board[3][6]));
		jTextField47.setText(String.valueOf(board[3][7]));
		jTextField48.setText(String.valueOf(board[3][8]));
		jTextField49.setText(String.valueOf(board[4][6]));
		jTextField50.setText(String.valueOf(board[4][7]));
		jTextField51.setText(String.valueOf(board[4][8]));
		jTextField52.setText(String.valueOf(board[5][6]));
		jTextField53.setText(String.valueOf(board[5][7]));
		jTextField54.setText(String.valueOf(board[5][8]));

		// seventh block

		jTextField55.setText(String.valueOf(board[6][0]));
		jTextField56.setText(String.valueOf(board[6][1]));
		jTextField57.setText(String.valueOf(board[6][2]));
		jTextField58.setText(String.valueOf(board[7][0]));
		jTextField59.setText(String.valueOf(board[7][1]));
		jTextField60.setText(String.valueOf(board[7][2]));
		jTextField61.setText(String.valueOf(board[8][0]));
		jTextField62.setText(String.valueOf(board[8][1]));
		jTextField63.setText(String.valueOf(board[8][2]));

		// eighth block

		jTextField64.setText(String.valueOf(board[6][3]));
		jTextField65.setText(String.valueOf(board[6][4]));
		jTextField66.setText(String.valueOf(board[6][5]));
		jTextField67.setText(String.valueOf(board[7][3]));
		jTextField68.setText(String.valueOf(board[7][4]));
		jTextField69.setText(String.valueOf(board[7][5]));
		jTextField70.setText(String.valueOf(board[8][3]));
		jTextField71.setText(String.valueOf(board[8][4]));
		jTextField72.setText(String.valueOf(board[8][5]));

		// ninth block

		jTextField73.setText(String.valueOf(board[6][6]));
		jTextField74.setText(String.valueOf(board[6][7]));
		jTextField75.setText(String.valueOf(board[6][8]));
		jTextField76.setText(String.valueOf(board[7][6]));
		jTextField77.setText(String.valueOf(board[7][7]));
		jTextField78.setText(String.valueOf(board[7][8]));
		jTextField79.setText(String.valueOf(board[8][6]));
		jTextField80.setText(String.valueOf(board[8][7]));
		jTextField81.setText(String.valueOf(board[8][8]));
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SudokuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SudokuFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton solveButton;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField15;
	private javax.swing.JTextField jTextField16;
	private javax.swing.JTextField jTextField17;
	private javax.swing.JTextField jTextField18;
	private javax.swing.JTextField jTextField19;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField20;
	private javax.swing.JTextField jTextField21;
	private javax.swing.JTextField jTextField22;
	private javax.swing.JTextField jTextField23;
	private javax.swing.JTextField jTextField24;
	private javax.swing.JTextField jTextField25;
	private javax.swing.JTextField jTextField26;
	private javax.swing.JTextField jTextField27;
	private javax.swing.JTextField jTextField28;
	private javax.swing.JTextField jTextField29;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField30;
	private javax.swing.JTextField jTextField31;
	private javax.swing.JTextField jTextField32;
	private javax.swing.JTextField jTextField33;
	private javax.swing.JTextField jTextField34;
	private javax.swing.JTextField jTextField35;
	private javax.swing.JTextField jTextField36;
	private javax.swing.JTextField jTextField37;
	private javax.swing.JTextField jTextField38;
	private javax.swing.JTextField jTextField39;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField40;
	private javax.swing.JTextField jTextField41;
	private javax.swing.JTextField jTextField42;
	private javax.swing.JTextField jTextField43;
	private javax.swing.JTextField jTextField44;
	private javax.swing.JTextField jTextField45;
	private javax.swing.JTextField jTextField46;
	private javax.swing.JTextField jTextField47;
	private javax.swing.JTextField jTextField48;
	private javax.swing.JTextField jTextField49;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField50;
	private javax.swing.JTextField jTextField51;
	private javax.swing.JTextField jTextField52;
	private javax.swing.JTextField jTextField53;
	private javax.swing.JTextField jTextField54;
	private javax.swing.JTextField jTextField55;
	private javax.swing.JTextField jTextField56;
	private javax.swing.JTextField jTextField57;
	private javax.swing.JTextField jTextField58;
	private javax.swing.JTextField jTextField59;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField60;
	private javax.swing.JTextField jTextField61;
	private javax.swing.JTextField jTextField62;
	private javax.swing.JTextField jTextField63;
	private javax.swing.JTextField jTextField64;
	private javax.swing.JTextField jTextField65;
	private javax.swing.JTextField jTextField66;
	private javax.swing.JTextField jTextField67;
	private javax.swing.JTextField jTextField68;
	private javax.swing.JTextField jTextField69;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField70;
	private javax.swing.JTextField jTextField71;
	private javax.swing.JTextField jTextField72;
	private javax.swing.JTextField jTextField73;
	private javax.swing.JTextField jTextField74;
	private javax.swing.JTextField jTextField75;
	private javax.swing.JTextField jTextField76;
	private javax.swing.JTextField jTextField77;
	private javax.swing.JTextField jTextField78;
	private javax.swing.JTextField jTextField79;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField80;
	private javax.swing.JTextField jTextField81;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration
}
